services:

  # Database Migrations Service (runs once on deploy)
  - type: web
    name: simstudio-migrations
    env: docker
    dockerfilePath: ./docker/app.Dockerfile
    dockerContext: .
    dockerCommand: cd packages/db && bun run db:migrate && sleep infinity
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: simstudio-db
          property: connectionString

  # Main Sim Studio Application
  - type: web
    name: simstudio-app
    env: docker
    dockerfilePath: ./docker/app.Dockerfile
    dockerContext: .
    dockerCommand: cd apps/sim && bun run start
    plan: standard
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: simstudio-db
          property: connectionString
      - key: BETTER_AUTH_URL
        fromService:
          type: web
          name: simstudio-app
          property: host
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: simstudio-app
          property: host
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SOCKET_SERVER_URL
        fromService:
          type: web
          name: simstudio-realtime
          property: host
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: simstudio-realtime
          property: host
      - key: COPILOT_API_KEY
        sync: false
      - key: SIM_AGENT_API_URL
        sync: false
      - key: OLLAMA_URL
        sync: false

  # Realtime Socket Server
  - type: web
    name: simstudio-realtime
    env: docker
    dockerfilePath: ./docker/realtime.Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: simstudio-db
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          type: web
          name: simstudio-app
          property: host
      - key: BETTER_AUTH_URL
        fromService:
          type: web
          name: simstudio-app
          property: host
      - key: BETTER_AUTH_SECRET
        fromService:
          type: web
          name: simstudio-app
          envVarKey: BETTER_AUTH_SECRET

databases:
  - name: simstudio-db
    databaseName: simstudio
    user: postgres
    plan: starter
    region: oregon
    # Note: Render PostgreSQL databases don't support custom Dockerfiles
    # You'll need to manually enable the pgvector extension after creation
    # Run: CREATE EXTENSION IF NOT EXISTS vector;
databases:
  - name: simstudio-db
    databaseName: simstudio
    plan: starter
    region: oregon
    postgresMajorVersion: 16
    # Note: After database creation, manually enable the pgvector extension by running:
    # CREATE EXTENSION IF NOT EXISTS vector;