services:
  # Main Sim Studio Application
  - type: web
    name: sim-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: bun install && cd apps/sim && NODE_OPTIONS="--max-old-space-size=4096" bun run build
    startCommand: cd apps/sim && bun run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SKIP_ENV_VALIDATION
        value: "true"
      - key: DOCKER_BUILD
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: sim-db
          property: connectionString
      - key: BETTER_AUTH_URL
        value: https://sim-app-3m6k.onrender.com
      - key: HOST
        value: "0.0.0.0"
      - key: NEXT_PUBLIC_APP_URL
        value: https://sim-app-3m6k.onrender.com
      - key: BETTER_AUTH_SECRET
        value: e95f824f0a10903d13a24aa63bca43b54fae43a33a911e10c597a680b178c859
      - key: INTERNAL_API_SECRET
        value: 6c5169f72f8fbd982550bb3f04a62e8b3ad11bd2101129bef82e39db92dbaa45
      - key: SOCKET_SERVER_URL
        fromService:
          type: web
          name: sim-realtime
          property: host
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: sim-realtime
          property: host

  # Realtime Socket Server
  - type: web
    name: sim-realtime
    runtime: node
    plan: free
    region: oregon
    buildCommand: bun install
    startCommand: cd apps/sim && bun run dev:sockets
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sim-db
          property: connectionString
      - key: NEXT_PUBLIC_APP_URL
        value: https://sim-app-3m6k.onrender.com
      - key: BETTER_AUTH_URL
        value: https://sim-app-3m6k.onrender.com
      - key: BETTER_AUTH_SECRET
        value: e95f824f0a10903d13a24aa63bca43b54fae43a33a911e10c597a680b178c859

databases:
  - name: sim-db
    databaseName: simstudio
    plan: free
    region: oregon