services:
  # Main Sim Studio Application
  - type: web
    name: sim-app
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: cd apps/sim && npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sim-db
          property: connectionString
      - key: BETTER_AUTH_URL
        value: https://sim-app-3m6k.onrender.com
      - key: HOST
        value: "0.0.0.0"
      - key: NEXT_PUBLIC_APP_URL
        value: https://sim-app-3m6k.onrender.com
      - key: BETTER_AUTH_SECRET
        value: e95f824f0a10903d13a24aa63bca43b54fae43a33a911e10c597a680b178c859
      - key: INTERNAL_API_SECRET
        value: 6c5169f72f8fbd982550bb3f04a62e8b3ad11bd2101129bef82e39db92dbaa45

jobs:
  - type: job
    name: sim-migrations
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install drizzle-orm postgres drizzle-kit
    startCommand: cd packages/db && npx drizzle-kit migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sim-db
          property: connectionString

databases:
  - name: sim-db
    databaseName: simstudio
    plan: free
    region: oregon